classes/form/cms_types_form.php
classes/local/lib.php
classes/local/model/cms.php
classes/local/model/cms_types.php
classes/local/renderer.php
classes/manage_content_types.php
db/install.xml
db/upgrade.php
lang/en/cms.php
lib.php
tests/renderer_test.php
version.php
view.php

Issue #14 Add mustache template to cms type.

---

classes/local/lib.php
lib.php

Issue #30: Temporarily prevent mod content from being cached.

---

classes/customfield/cmsfield_handler.php
classes/local/lib.php
classes/local/table/content_types_list.php
customfield.php
lang/en/cms.php
mod_form.php
version.php

Resolves #13.
Add custom field management to CMS type.
Add custom field display to CMS instance.
Add saving and add custom field data to forms.

Issue #13: Add support for custom fields.

---

classes/form/cms_types_form.php
classes/local/model/cms_types.php
classes/local/renderer.php
lang/en/cms.php
tests/renderer_test.php
version.php

Issue #34: Expose custom field data in templates.

---

classes/manage_content_types.php
customfield.php

Issue #28: Fix breadcrumb trails.

---

classes/form/cms_types_form.php
classes/local/lib.php
classes/local/model/cms_types.php
classes/local/renderer.php
classes/manage_content_types.php
lang/en/cms.php
lib.php
version.php

Issue #22: Add support for adding images to the CMS type template.

---

README.md
classes/form/cms_types_form.php
classes/local/datasource/base.php
classes/local/datasource/fields.php
classes/local/datasource/images.php
classes/local/datasource/site.php
classes/local/model/cms.php
classes/local/model/cms_types.php
classes/local/renderer.php
classes/local/table/content_types_list.php
classes/manage_content_types.php
lang/en/cms.php
mod_form.php
tests/datasource_base_test.php
tests/datasource_fields_test.php
tests/datasource_images_test.php
tests/datasource_site_test.php
tests/renderer_test.php
version.php

Issue #9: Refactor data to use a modular datasource system.

---

classes/local/lib.php
classes/local/model/cms_types.php
lib.php
tests/cms_instance_test.php
tests/fixtures/test_import_1.yml
version.php

Issue #60: Fix silly bug.

---

backup/moodle2/backup_cms_activity_task.class.php

Resolves #52 
This is just a placeholder. A more complete fix will be implemented for #20.

Issue #52: Add placeholder for backup_cms_activity_task

---

classes/helper.php
classes/local/datasource/base.php
classes/local/datasource/fields.php
classes/local/datasource/images.php
classes/local/lib.php
classes/local/model/cms_types.php
classes/local/table/content_types_list.php
classes/manage_content_types.php
lang/en/cms.php
lib.php
tests/cms_instance_test.php
tests/datasource_fields_test.php
tests/datasource_images_test.php
tests/datasource_site_test.php
tests/fixtures/test_import1_trait.php
tests/get_course_content_items_test.php
tests/renderer_test.php
version.php

Resolves #53
Also: Add a confirm popup when clicking on delete.
Remove ability to delete cms types that have instances.

Issue #53: Fix deleting to handle datasources.

---

classes/local/lib.php
classes/local/model/cms_types.php
classes/local/table/content_types_list.php
classes/manage_content_types.php
db/access.php
db/install.xml
db/upgrade.php
lang/en/cms.php
tests/get_course_content_items_test.php
version.php

Resolves #42
Add role to enable user to see all CMS types anyway.

Issue #42 - Add setting to allow CSM types to have optional listing in activity chooser.

---

classes/local/model/cms_types.php
classes/local/renderer.php

Issue #73: Add debug variable

---

classes/local/datasource/base.php
classes/local/datasource/roles.php
classes/local/lib.php
classes/local/model/cms_types.php
classes/local/model/persistent_extras.php
classes/manage_content_types.php
db/events.php
db/upgrade.php
lang/en/cms.php
tests/datasource_roles_test.php
tests/fixtures/roles_data.json
tests/fixtures/test_import2_trait.php
tests/fixtures/test_import_2.yml
tests/renderer_test.php

Issue #10: List roles associated with a course.

---

db/install.xml
db/upgrade.php
version.php

Issue #58: Update schema format.

---

classes/manage_content_types.php

Issue #81: Fix CMS type save and display crash.

---

classes/form/cms_types_form.php
classes/local/datasource/roles.php
classes/local/lib.php
classes/local/model/cms_types.php
classes/local/renderer.php
classes/manage_content_types.php
db/caches.php
db/install.xml
db/upgrade.php
lang/en/cms.php
mod_form.php
tests/cms_instance_test.php
tests/cms_types_test.php
tests/fixtures/test_import_1.yml
tests/fixtures/test_import_2.yml
tests/renderer_test.php
version.php

Issue #68: CMS name is derived from the CMS type config

---

classes/form/cms_types_form.php
classes/local/renderer.php
lang/en/cms.php
tests/renderer_test.php
version.php

Issue #71: make listing of mustache variables in CMS types form more readable

---

classes/form/cms_types_form.php
tests/cms_types_test.php

Issue #65: Validate mustache template before saving.

---

classes/form/cms_types_form.php
classes/local/datasource/images.php
classes/local/datasource/roles.php
classes/local/datasource/userlist.php
lang/en/cms.php
version.php

Issue #77: Add subheading for data sources in config and instance forms.

---

classes/form/cms_types_form.php
classes/local/model/cms_types.php
db/install.xml
db/upgrade.php
lang/en/cms.php
tests/cms_types_test.php
tests/datasource_base_test.php
tests/datasource_fields_test.php
tests/datasource_images_test.php
tests/datasource_roles_test.php
tests/datasource_site_test.php
tests/datasource_userlist_test.php
tests/fixtures/test_import_1.yml
tests/fixtures/test_import_2.yml
tests/get_course_content_items_test.php
tests/renderer_test.php
version.php

Issue #55: Add idnumber to cms_types.

---

classes/local/datasource/base.php
classes/local/datasource/base_mod_cms.php
classes/local/datasource/fields.php
classes/local/datasource/images.php
classes/local/datasource/roles.php
classes/local/datasource/traits/nullcache.php
classes/local/datasource/userlist.php
classes/local/renderer.php

Issue #98: Refactor to get the datasource to supply the cache object.

---

classes/local/datasource/base.php
classes/local/datasource/userlist.php
db/upgrade.php
tests/datasource_userlist_test.php
tests/fixtures/test_import_1.yml
tests/renderer_test.php
version.php

Issue #113: Fix regression caused by previous commit.

---

classes/form/cms_types_form.php
classes/local/lib.php
classes/local/model/cms_types.php
classes/local/renderer.php
classes/local/table/content_types_list.php
classes/manage_content_types.php
lang/en/cms.php
tests/cms_types_test.php
tests/fixtures/type_data.json
version.php

Resolves #18 
- Add ability to edit an icon file in CMS edit form
- Display icon on activity list.

Issue #18: Add support to add an icon to a CMS type.
